export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const GET_USER_LOGIN = "GET_USER_LOGIN";
export const ADD_TOKEN = "ADD_TOKEN";
